version: '2'
services:
  php:
    build: ./php/
    restart: always
    links:
      - mariadb
    ports:
      - 80:80
      - 443:443
  mariadb:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_USER: piwik 
      MYSQL_PASSWORD: Temple_46
      MYSQL_DATABASE: piwik_db
    ports:
      - 3306:3306
